// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpmyursjpbscrfbljtha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwbXl1cnNqcGJzY3JmYmxqdGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzY2MzQsImV4cCI6MjA3MDMxMjYzNH0.tbP9hGf6x1NiP0thD6d9wyP_-LfxTjRpQjDVRE80h9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});